In [40]:
import pandas as pd
import numpy as np
import os, sys

In [41]:
#Read in UKBB Demographics
ukbb = pd.read_csv(r"C:\Users\Huy\Desktop\Dataset\ukb_demographics.txt", sep='\t')
ukbb

,eid,Sex,TownsendIndex,EthnicBackground,Age,AssessmentCenter,EthnicGroup
0,5713894.0,Male,-1.63069,British,60.0,11001.0,White
1,2048882.0,Female,-4.55284,British,54.0,11018.0,White
2,1748132.0,Female,-2.80459,British,64.0,11014.0,White
3,3772083.0,Male,-1.24212,British,47.0,11020.0,White
4,4376107.0,Female,-4.07395,Any other white background,63.0,11007.0,White
...,...,...,...,...,...,...,...
501112,2637602.0,Male,-2.81248,British,58.0,11010.0,White
501113,2397350.0,Male,4.47078,British,51.0,11012.0,White
501114,3905086.0,Female,1.69870,British,54.0,11016.0,White
501115,5844444.0,Male,-4.01812,British,43.0,11016.0,White
501116,3002154.0,Female,-6.25826,British,60.0,11007.0,White

In [42]:
#Read in Latinos Country of Origin
latinos_country = pd.read_csv(r"C:\Users\Huy\Desktop\Dataset\latinos_countryOfOrigin.txt", sep='\t')
latinos_country

            eid  CountryCode    Country  Continent
0     2002932.0        603.0     Brazil        600
1     5385995.0        603.0     Brazil        600
2     5264380.0        603.0     Brazil        600
3     5088773.0        603.0     Brazil        600
4     2522434.0        603.0     Brazil        600
...         ...          ...        ...        ...
1125  2023014.0        416.0  Guatemala        400
1126  2504745.0        416.0  Guatemala        400
1127  1538342.0        416.0  Guatemala        400
1128  4351326.0        424.0  Nicaragua        400
1129  1976600.0        424.0  Nicaragua        400

[1130 rows x 4 columns]

In [43]:
#Get Latino cohort by matching EID with UKBB Demographic and Latino Country of Origin
ukbb_new = pd.merge(latinos_country, ukbb, how='inner', on=['eid'])
ukbb_new['EthnicGroup'] = ukbb_new['EthnicGroup'].replace(['White', 'OtherEthnicity', 'Mixed', 'Chinese', 'Asian', 'Black'],'Latino')
ukbb_new

,eid,CountryCode,Country,Continent,Sex,TownsendIndex,EthnicBackground,Age,AssessmentCenter,EthnicGroup
0,2002932.0,603.0,Brazil,600,Female,-1.139390,British,69.0,11007.0,Latino
1,5385995.0,603.0,Brazil,600,Female,-2.166550,Other ethnic group,42.0,11014.0,Latino
2,5264380.0,603.0,Brazil,600,Male,2.296130,Any other white background,65.0,11018.0,Latino
3,5088773.0,603.0,Brazil,600,Male,7.330950,Any other white background,44.0,11012.0,Latino
4,2522434.0,603.0,Brazil,600,Male,5.077420,Any other white background,42.0,11018.0,Latino
...,...,...,...,...,...,...,...,...,...,...
1107,2023014.0,416.0,Guatemala,400,Male,-0.261213,British,54.0,11018.0,Latino
1108,2504745.0,416.0,Guatemala,400,Female,-4.057050,Any other mixed background,43.0,11017.0,Latino
1109,1538342.0,416.0,Guatemala,400,Female,-5.821450,British,66.0,11007.0,Latino
1110,4351326.0,424.0,Nicaragua,400,Female,-3.384610,British,47.0,11016.0,Latino
1111,1976600.0,424.0,Nicaragua,400,Female,3.320920,Any other white background,69.0,11020.0,Latino

In [44]:
#Retrieving the ancestry data
ancestry = pd.read_csv(r"C:\Users\Huy\Desktop\Dataset\latino_admixture_k4.txt", sep='\t')
ancestry = ancestry.dropna()
ancestry = ancestry.astype({"IID": 'int64'})
ancestry

,IID,FamID,EastAsian,African,European,Native,Country,Population,SuperPop
0,1003675,1003675,0.027590,0.027961,0.937699,0.006750,Brazil,Brazil,Latinos in the UK
1,1009347,1009347,0.014956,0.027254,0.943062,0.014727,Uruguay,Uruguay,Latinos in the UK
2,1011106,1011106,0.007435,0.339127,0.236250,0.417189,Brazil,Brazil,Latinos in the UK
3,1014677,1014677,0.028814,0.214989,0.734407,0.021790,Brazil,Brazil,Latinos in the UK
4,1015796,1015796,0.002952,0.060546,0.445552,0.490951,Colombia,Colombia,Latinos in the UK
...,...,...,...,...,...,...,...,...,...
1079,5992098,5992098,0.008756,0.003879,0.957751,0.029614,Uruguay,Uruguay,Latinos in the UK
1080,5999691,5999691,0.010235,0.040331,0.797386,0.152047,Argentina,Argentina,Latinos in the UK
1081,6003688,6003688,0.003014,0.010784,0.238495,0.747707,Peru,Peru,Latinos in the UK
1082,6006153,6006153,0.023192,0.323885,0.507963,0.144960,Brazil,Brazil,Latinos in the UK
1083,6017047,6017047,0.009365,0.089697,0.481055,0.419883,Colombia,Colombia,Latinos in the UK

In [45]:
#Latino cohort
temp1 = pd.merge(ukbb_new, ancestry, left_on='eid', right_on='IID', how='left')
temp1

,eid,CountryCode,Country_x,Continent,Sex,TownsendIndex,EthnicBackground,Age,AssessmentCenter,EthnicGroup,IID,FamID,EastAsian,African,European,Native,Country_y,Population,SuperPop
0,2002932.0,603.0,Brazil,600,Female,-1.139390,British,69.0,11007.0,Latino,2002932.0,2002932,0.028159,0.001727,0.944278,0.025835,Brazil,Brazil,Latinos in the UK
1,5385995.0,603.0,Brazil,600,Female,-2.166550,Other ethnic group,42.0,11014.0,Latino,5385995.0,5385995,0.003805,0.260520,0.630779,0.104896,Brazil,Brazil,Latinos in the UK
2,5264380.0,603.0,Brazil,600,Male,2.296130,Any other white background,65.0,11018.0,Latino,5264380.0,5264380,0.012899,0.047668,0.853945,0.085488,Brazil,Brazil,Latinos in the UK
3,5088773.0,603.0,Brazil,600,Male,7.330950,Any other white background,44.0,11012.0,Latino,5088773.0,5088773,0.012409,0.016347,0.952571,0.018674,Brazil,Brazil,Latinos in the UK
4,2522434.0,603.0,Brazil,600,Male,5.077420,Any other white background,42.0,11018.0,Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,2023014.0,416.0,Guatemala,400,Male,-0.261213,British,54.0,11018.0,Latino,2023014.0,2023014,0.014347,0.011462,0.954814,0.019376,Guatemala,Guatemala,Latinos in the UK
1108,2504745.0,416.0,Guatemala,400,Female,-4.057050,Any other mixed background,43.0,11017.0,Latino,2504745.0,2504745,0.022893,0.083996,0.518464,0.374646,Guatemala,Guatemala,Latinos in the UK
1109,1538342.0,416.0,Guatemala,400,Female,-5.821450,British,66.0,11007.0,Latino,1538342.0,1538342,0.024056,0.045030,0.536728,0.394186,Guatemala,Guatemala,Latinos in the UK
1110,4351326.0,424.0,Nicaragua,400,Female,-3.384610,British,47.0,11016.0,Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,1976600.0,424.0,Nicaragua,400,Female,3.320920,Any other white background,69.0,11020.0,Latino,1976600.0,1976600,0.011981,0.003922,0.965218,0.018879,Nicaragua,Nicaragua,Latinos in the UK

In [8]:
#parquet_file1 = r"C:\Users\Huy\Desktop\Dataset\FinalTotal_cleaned_Binned_Normalized.parquet"
#df1 = pd.read_parquet(parquet_file1)
#alcohol = df1.filter(regex='alcohol_drinker_status', axis=1)
#weight = df1.filter(regex='weight', axis=1)

In [9]:
#alcohol

,alcohol_drinker_status_f20117_0_0_Current,alcohol_drinker_status_f20117_0_0_Never,alcohol_drinker_status_f20117_0_0_Prefer not to answer,alcohol_drinker_status_f20117_0_0_Previous
0,1,0,0,0
1,0,1,0,0
2,1,0,0,0
3,1,0,0,0
4,1,0,0,0
...,...,...,...,...
502636,1,0,0,0
502637,1,0,0,0
502638,1,0,0,0
502639,1,0,0,0
502640,1,0,0,0

In [46]:
#Read in disparate disease list
disparate = pd.read_csv(r"C:\Users\Huy\Desktop\Dataset\disparate_diseases.txt", sep='\t')
disparate

,Disease,Distance,Prevalence_latino,Prevalence_whiteBrit
0,785.0_Abdominal_pain.txt,3.297342,14.43,11.15
1,585.3_Chronic_renal_failure__CKD_.txt,2.856768,0.09,0.64
2,401.1_Essential_hypertension.txt,2.848676,13.29,16.13
3,854.0_Complications_of_cardiac_vascular_device...,2.624323,0.09,0.56
4,496.0_Chronic_airway_obstruction.txt,2.609107,0.38,1.77
...,...,...,...,...
660,446.5_Giant_cell_arteritis.txt,0.000000,0.09,0.09
661,284.0_Aplastic_anemia.txt,0.000000,0.09,0.09
662,433.8_Late_effects_of_cerebrovascular_disease.txt,0.000000,0.27,0.27
663,275.5_Disorders_of_calcium_phosphorus_metaboli...,0.000000,0.27,0.27
664,687.1_Rash_and_other_nonspecific_skin_eruption...,0.000000,0.63,0.63

In [47]:
folder = os.listdir("C:\\Users\\Huy\\Desktop\\Dataset\\phecode_cohorts")
list_top = []
for disease in disparate.head(10).Disease: #Go through only top 10 disparate
    list_top.append(disease)
ukbb_update = pd.DataFrame(columns = [])
for file in folder:
    if file in list_top:
        disease_df = pd.read_csv(r"C:\\Users\\Huy\\Desktop\\Dataset\\phecode_cohorts\\" + file, sep='\t')
        disease_df["Disease"] = file #Get name of disease
        temp2 = pd.merge(temp1, disease_df, how='inner', on=['eid']) #Merge disease file and Latino cohort
        ukbb_update = ukbb_update.append(temp2) #Add to empty df and repeat
ukbb_update

,eid,CountryCode,Country_x,Continent,Sex,TownsendIndex,EthnicBackground,Age,AssessmentCenter,EthnicGroup,...,FamID,EastAsian,African,European,Native,Country_y,Population,SuperPop,Status,Disease
0,2002932.0,603.0,Brazil,600,Female,-1.139390,British,69.0,11007.0,Latino,...,2002932,0.028159,0.001727,0.944278,0.025835,Brazil,Brazil,Latinos in the UK,0,401.1_Essential_hypertension.txt
1,5385995.0,603.0,Brazil,600,Female,-2.166550,Other ethnic group,42.0,11014.0,Latino,...,5385995,0.003805,0.260520,0.630779,0.104896,Brazil,Brazil,Latinos in the UK,0,401.1_Essential_hypertension.txt
2,5264380.0,603.0,Brazil,600,Male,2.296130,Any other white background,65.0,11018.0,Latino,...,5264380,0.012899,0.047668,0.853945,0.085488,Brazil,Brazil,Latinos in the UK,1,401.1_Essential_hypertension.txt
3,5088773.0,603.0,Brazil,600,Male,7.330950,Any other white background,44.0,11012.0,Latino,...,5088773,0.012409,0.016347,0.952571,0.018674,Brazil,Brazil,Latinos in the UK,0,401.1_Essential_hypertension.txt
4,2522434.0,603.0,Brazil,600,Male,5.077420,Any other white background,42.0,11018.0,Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,401.1_Essential_hypertension.txt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,3771976.0,416.0,Guatemala,400,Female,-4.443490,Other ethnic group,52.0,11009.0,Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,854.0_Complications_of_cardiac_vascular_device...
1062,2023014.0,416.0,Guatemala,400,Male,-0.261213,British,54.0,11018.0,Latino,...,2023014,0.014347,0.011462,0.954814,0.019376,Guatemala,Guatemala,Latinos in the UK,0,854.0_Complications_of_cardiac_vascular_device...
1063,2504745.0,416.0,Guatemala,400,Female,-4.057050,Any other mixed background,43.0,11017.0,Latino,...,2504745,0.022893,0.083996,0.518464,0.374646,Guatemala,Guatemala,Latinos in the UK,0,854.0_Complications_of_cardiac_vascular_device...
1064,1538342.0,416.0,Guatemala,400,Female,-5.821450,British,66.0,11007.0,Latino,...,1538342,0.024056,0.045030,0.536728,0.394186,Guatemala,Guatemala,Latinos in the UK,0,854.0_Complications_of_cardiac_vascular_device...
1065,4351326.0,424.0,Nicaragua,400,Female,-3.384610,British,47.0,11016.0,Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,854.0_Complications_of_cardiac_vascular_device...

In [48]:
#Clean-up and removal of unnecessary columns
del ukbb_update["CountryCode"]
del ukbb_update["Country_x"]
del ukbb_update["Continent"]
del ukbb_update["AssessmentCenter"]
del ukbb_update["IID"]
del ukbb_update["FamID"]
del ukbb_update["SuperPop"]
del ukbb_update["Population"]
ukbb_update = ukbb_update.rename(columns={'eid':"EID"})
ukbb_update = ukbb_update.rename(columns={'Country_y':"Country"})
ukbb_update = ukbb_update[["EID", "Age", "Sex", "TownsendIndex", "EthnicBackground", "EthnicGroup", "Status", "Disease", "EastAsian", "African", "European", "Native", "Country"]]
ukbb_update

,EID,Age,Sex,TownsendIndex,EthnicBackground,EthnicGroup,Status,Disease,EastAsian,African,European,Native,Country
0,2002932.0,69.0,Female,-1.139390,British,Latino,0,401.1_Essential_hypertension.txt,0.028159,0.001727,0.944278,0.025835,Brazil
1,5385995.0,42.0,Female,-2.166550,Other ethnic group,Latino,0,401.1_Essential_hypertension.txt,0.003805,0.260520,0.630779,0.104896,Brazil
2,5264380.0,65.0,Male,2.296130,Any other white background,Latino,1,401.1_Essential_hypertension.txt,0.012899,0.047668,0.853945,0.085488,Brazil
3,5088773.0,44.0,Male,7.330950,Any other white background,Latino,0,401.1_Essential_hypertension.txt,0.012409,0.016347,0.952571,0.018674,Brazil
4,2522434.0,42.0,Male,5.077420,Any other white background,Latino,0,401.1_Essential_hypertension.txt,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,3771976.0,52.0,Female,-4.443490,Other ethnic group,Latino,0,854.0_Complications_of_cardiac_vascular_device...,NaN,NaN,NaN,NaN,NaN
1062,2023014.0,54.0,Male,-0.261213,British,Latino,0,854.0_Complications_of_cardiac_vascular_device...,0.014347,0.011462,0.954814,0.019376,Guatemala
1063,2504745.0,43.0,Female,-4.057050,Any other mixed background,Latino,0,854.0_Complications_of_cardiac_vascular_device...,0.022893,0.083996,0.518464,0.374646,Guatemala
1064,1538342.0,66.0,Female,-5.821450,British,Latino,0,854.0_Complications_of_cardiac_vascular_device...,0.024056,0.045030,0.536728,0.394186,Guatemala
1065,4351326.0,47.0,Female,-3.384610,British,Latino,0,854.0_Complications_of_cardiac_vascular_device...,NaN,NaN,NaN,NaN,NaN

In [58]:
temp_df2 = pd.DataFrame(columns = [])
disease_list_done = []
for disease in disparate.head(10).Disease: #Only look at top 10 disparate
    if disease in ["426.91_Cardiac_pacemaker_in_situ.txt"]:
        if disease not in disease_list_done:
            ageDict = {} #Keep track of age for every disease
            sexDict = {} #Keep track of sex for every disease
            Total = 0 #Keep track of total for every disease
            temp_df1 = ukbb_update[ukbb_update["Disease"] == disease] #Create tempory df of disease you want to look at
            for num in temp_df1.Age: #Go through participant age and add to dictionary
                if num not in ageDict:
                    ageDict[num] = 1
                else:
                    ageDict[num] = ageDict[num] + 1
            for gender in temp_df1.Sex: #Go through participant gender and add to dictionary
                if gender not in sexDict:
                    sexDict[gender] = 1
                    Total += 1
                else:
                    sexDict[gender] = sexDict[gender] + 1
                    Total += 1
            for index, row in temp_df1.iterrows(): #Go through every row in tempory df of the certain disease
                row["AgeFraction"] = (ageDict[row.Age] / Total) #Create column for age fraction
                row["SexFraction"] = (sexDict[row.Sex] / Total) #Create column for sex fraction
                temp_df2 = temp_df2.append(row) #Add new row to empty df and repeat
temp_df2

,African,Age,AgeFraction,Country,Disease,EID,EastAsian,EthnicBackground,EthnicGroup,European,Native,Sex,SexFraction,Status,TownsendIndex
0,0.001727,69.0,0.016917,Brazil,426.91_Cardiac_pacemaker_in_situ.txt,2002932.0,0.028159,British,Latino,0.944278,0.025835,Female,0.667293,0.0,-1.139390
1,0.260520,42.0,0.038534,Brazil,426.91_Cardiac_pacemaker_in_situ.txt,5385995.0,0.003805,Other ethnic group,Latino,0.630779,0.104896,Female,0.667293,0.0,-2.166550
2,0.047668,65.0,0.021617,Brazil,426.91_Cardiac_pacemaker_in_situ.txt,5264380.0,0.012899,Any other white background,Latino,0.853945,0.085488,Male,0.332707,0.0,2.296130
3,0.016347,44.0,0.056391,Brazil,426.91_Cardiac_pacemaker_in_situ.txt,5088773.0,0.012409,Any other white background,Latino,0.952571,0.018674,Male,0.332707,0.0,7.330950
4,NaN,42.0,0.038534,NaN,426.91_Cardiac_pacemaker_in_situ.txt,2522434.0,NaN,Any other white background,Latino,NaN,NaN,Male,0.332707,0.0,5.077420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,0.011462,54.0,0.031015,Guatemala,426.91_Cardiac_pacemaker_in_situ.txt,2023014.0,0.014347,British,Latino,0.954814,0.019376,Male,0.332707,0.0,-0.261213
1060,0.083996,43.0,0.046053,Guatemala,426.91_Cardiac_pacemaker_in_situ.txt,2504745.0,0.022893,Any other mixed background,Latino,0.518464,0.374646,Female,0.667293,0.0,-4.057050
1061,0.045030,66.0,0.019737,Guatemala,426.91_Cardiac_pacemaker_in_situ.txt,1538342.0,0.024056,British,Latino,0.536728,0.394186,Female,0.667293,0.0,-5.821450
1062,NaN,47.0,0.046053,NaN,426.91_Cardiac_pacemaker_in_situ.txt,4351326.0,NaN,British,Latino,NaN,NaN,Female,0.667293,0.0,-3.384610
1063,0.003922,69.0,0.016917,Nicaragua,426.91_Cardiac_pacemaker_in_situ.txt,1976600.0,0.011981,Any other white background,Latino,0.965218,0.018879,Female,0.667293,0.0,3.320920

In [59]:
#Reorder of columns
del temp_df2["Country"]
new_df = temp_df2[["EID", "EastAsian", "African", "European", "Native", "EthnicBackground", "EthnicGroup", "TownsendIndex", "Age", "AgeFraction", "Sex", "SexFraction", "Disease", "Status"]]
new_df["EID"] = new_df["EID"].astype(int)
new_df["Age"] = new_df["Age"].astype(int)
new_df["Status"] = new_df["Status"].astype(int)
new_df

,EID,EastAsian,African,European,Native,EthnicBackground,EthnicGroup,TownsendIndex,Age,AgeFraction,Sex,SexFraction,Disease,Status
0,2002932,0.028159,0.001727,0.944278,0.025835,British,Latino,-1.139390,69,0.016917,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0
1,5385995,0.003805,0.260520,0.630779,0.104896,Other ethnic group,Latino,-2.166550,42,0.038534,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0
2,5264380,0.012899,0.047668,0.853945,0.085488,Any other white background,Latino,2.296130,65,0.021617,Male,0.332707,426.91_Cardiac_pacemaker_in_situ.txt,0
3,5088773,0.012409,0.016347,0.952571,0.018674,Any other white background,Latino,7.330950,44,0.056391,Male,0.332707,426.91_Cardiac_pacemaker_in_situ.txt,0
4,2522434,NaN,NaN,NaN,NaN,Any other white background,Latino,5.077420,42,0.038534,Male,0.332707,426.91_Cardiac_pacemaker_in_situ.txt,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,2023014,0.014347,0.011462,0.954814,0.019376,British,Latino,-0.261213,54,0.031015,Male,0.332707,426.91_Cardiac_pacemaker_in_situ.txt,0
1060,2504745,0.022893,0.083996,0.518464,0.374646,Any other mixed background,Latino,-4.057050,43,0.046053,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0
1061,1538342,0.024056,0.045030,0.536728,0.394186,British,Latino,-5.821450,66,0.019737,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0
1062,4351326,NaN,NaN,NaN,NaN,British,Latino,-3.384610,47,0.046053,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0
1063,1976600,0.011981,0.003922,0.965218,0.018879,Any other white background,Latino,3.320920,69,0.016917,Female,0.667293,426.91_Cardiac_pacemaker_in_situ.txt,0

In [60]:
new_df.to_csv('top10_disparate_disease_consolidated_latino_treatment.txt', index=False, sep='\t')